version: '3.8'

services:
  pg_cluster:
    image: ghcr.io/zalando/spilo-15:2.1-p6
    environment:
      CLUSTER_NAME: my-postgres
      CLUSTER_SCOPE: my-postgres
      SCOPE: my-postgres
      PATRONI_POSTGRESQL_DATA_DIR: /home/postgres/pgdata/pgroot/data
      PATRONI_KUBERNETES_USE_ENDPOINTS: 'false'
      PATRONI_LOG_LEVEL: INFO
      PATRONI_ETCD_HOSTS: etcd:2379
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: replpassword
      PATRONI_SUPERUSER_PASSWORD: adminpassword
    deploy:
      replicas: ${PG_NODES:-4}
      restart_policy:
        condition: on-failure
    networks:
      - pgnet

  etcd:
    image: quay.io/coreos/etcd:v3.5
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - pgnet

networks:
  pgnet:
    driver: overlay
